### ISSUE TITLE
does not work at .com/forum

### ISSUE THREAD

**Issue by AliCihan** [oplik0/nodebb-plugin-two-way-block#12]
Hi oplik0, 

we did our tests at dev.ourwebsite.com and everything worked beautifully, however we realized today that it is not working in our prod forum which is at ourwebsite.com/forum ... 

Any idea why it could be?

**Comment by AliCihan** [comment]
We do have these hooks installed although we are using 1.13.3:

filter:user.blocks.filter 1 hooks
action:user.blocks.add 1 hooks
action:user.blocks.remove 1 hooks

**Comment by oplik0** [comment]
Well, that doesn't mean anything unfortunately:
![image](https://user-images.githubusercontent.com/25460763/83554774-cf02c300-a4fc-11ea-8816-e4ef64656c69.png)
NodeBB isn't actually basing hooks in the admin hooks menu on the ones that can be fired, but rather the ones that are registered by plugins.

Could you send the output of `git rev-parse HEAD`? I want to know for sure if you're running 1.13.3 from before the hook addition (even current `master` shows up as 1.13.3 in ACP) or if it's a problem with the plugin.

Sorry for taking so long to reply, but I had to fix my testing server (err... I kinda lost npm. Don't ask how.) and the plugin still seems to work for me.

**Comment by AliCihan** [comment]
I wrote "git rev-parse --abbrev-ref HEAD" both in our development forum and production forum... 

in the development forum, it returns "block_hooks"

in the production forum, it returns "HEAD"

If I remove "--abbrev-ref" from the code, it gives me long alphanumeric codes (both are different), do you want to see these codes? 

Does this mean that we just forgot to update hooks in our production forum, just thought we did :) and bothered you for nothing ? :)

**Comment by oplik0** [comment]
Yes, it'd be useful :) The long alphanumeric codes are git references that refer to a hash of a specific commit. I only need the one from the production server, since it's the one that has a problem. If it's a commit after the one with block hooks, I'll definitely have to look into that since it'd mean some commit broke the plugin.

**Comment by AliCihan** [comment]
ok, no problem... 

This is the code from the production forum:
5db31e7e9548760a3d0dce15504cc1729f2347af

This is from the development forum:
c4545381d760ee1a9885af7b56dfa045cee7cd94

Thanks a lot...

**Comment by oplik0** [comment]
Yup. You can see the `/src/user/blocks.js` from the point of that commit [here](https://github.com/NodeBB/NodeBB/blob/5db31e7e9548760a3d0dce15504cc1729f2347af/src/user/blocks.js) and it doesn't have the any `plugins.fireHook` calls.
Contrast it to the [code at the point of the commit](https://github.com/NodeBB/NodeBB/blob/c4545381d760ee1a9885af7b56dfa045cee7cd94/src/user/blocks.js) from the development server.

However, actually thanks to this thread, I noticed that `1.13.x` branch was actually updated and is at `1.13.4-5` (that is - 5th pre-release of 1.13.4) so while technically it's a pre-release, it doesn't contain any breaking changes like 1.14.0 that's also in a pre-release stage right now (I think for now it mostly changes the ACP, moving all the pages there around), so you can just upgrade it like you would to a next `1.13.x` version (that is:
```bash
git fetch
git reset --hard origin/v1.13.x
```
according to the [upgrade docs](https://docs.nodebb.org/configuring/upgrade/)
).

I'm gonna close this issue then. Comment here and I'll reopen it or open another one if the plugin still doesn't work after an update.

**Comment by AliCihan** [comment]
thanks a lot @oplik0 , after upgrading to 1.13.4-5 , our problem is resolved...
