### ISSUE TITLE
Slow forum and 503

### ISSUE THREAD

**Issue by OAT75** [oplik0/nodebb-plugin-two-way-block#121]
Plugin makes forum slow and receive excess load error: 503.  Running version 2.0.1

**Comment by oplik0** [comment]
Hmm... Are you by chance running more than one NodeBB process? If so, I'll release something that might fix it in a moment. Otherwise I guess I'll have to try replicating it, since it works fine in my smaller scale tests. v2 hasn't changed anything relevant to this plugin fortunately.
