### ISSUE TITLE
Integrate with nodebb-plugin-browsing-users

### ISSUE THREAD

**Issue by oplik0** [oplik0/nodebb-plugin-two-way-block#61]
_Originally posted by @AliCihan in https://github.com/oplik0/nodebb-plugin-two-way-block/issues/58#issuecomment-1000922004_

> I have one more question (more like a feature request if you see this as a good addition to the plugin). We use the "browsing users" plugin, so avatars of the users browsing the same topic can be seen.  Do you think it is easy to block the appearance of the avatar of the blocked person on these pages?
> So, in the end, this plugin will be more like the "blocking" function of the many social media sites. You do not see the blocked person and also his/her posts; and vice versa...

To do:
- [x] ~Investigate how exactly [nodebb-plugin-browsing-users](https://github.com/barisusakli/nodebb-plugin-browsing-users) works to determine if it's even feasible~ it's not without modifying the plugin itself.
- [ ] Modify the plugin so it is possible
- [x] ~If that's the case, make the plugin hide blocked users (both ways) from being displayed as browsing a topic~ no modification necessary

**Comment by AliCihan** [comment]
@oplik0 thanks a lot.

**Comment by oplik0** [comment]
Well, I've run into a bit of an issue here. I'm able to hide users from browsing users, but I'm unable to do it **only** there, since the only call I can intercept for this purpose is `user.getFields`.

It has a fun consequence of creating basically a super-block, where the blocked user is no longer able to see the one who blocked them (as in, nowhere on the website. They see them as Guest in some places and not at all in others), but the issue is that if I do also filter for blocked users there it becomes impossible to **unblock** someone. So either this super-block is one-sided, but reversed (the blocked user doesn't see you at all, but you still see them), or it makes the whole block feature irreversible :D

I think I'll ask if it's okay to add some way of controlling the displayed browsing users to the original plugin, and if not I can always make a fork that'd add it, if you're fine with that way of doing it @AliCihan

**Comment by oplik0** [comment]
Well, now we're waiting for upstream :)

No modification of this plugin is required though, as it was simple enough to just plug into existing NodeBB API for filtering blocked users (which this plugin extends already), so I'll publish a new version in a moment
